name: pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Tests
        run: npm run test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: eu-west-1

      - name: Deploy
        run: npm run deploy

      - name: Get Endpoints
        id: endpoints
        run: |
          echo "put_endpoint=$(npx sls info --verbose | grep 'PUT -' | awk '{print $3}')" >> "$GITHUB_OUTPUT"
          echo "get_endpoint=$(npx sls info --verbose | grep 'GET -' | awk '{print $3}')" >> "$GITHUB_OUTPUT"

      - name: Test Endpoints
        run: |
          put_endpoint="${{ steps.endpoints.outputs.put_endpoint }}"
          get_endpoint="${{ steps.endpoints.outputs.get_endpoint }}"

          echo $put_endpoint 
          echo $get_endpoint


          
